// Auto-generated by Supabase MCP — do not edit manually
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      audit_log: {
        Row: {
          accion: string
          created_at: string
          id: number
          ip_address: unknown
          registro_id: string
          tabla_afectada: string
          usuario_id: string | null
          valor_anterior: Json | null
          valor_nuevo: Json | null
        }
        Insert: {
          accion: string
          created_at?: string
          id?: number
          ip_address?: unknown
          registro_id: string
          tabla_afectada: string
          usuario_id?: string | null
          valor_anterior?: Json | null
          valor_nuevo?: Json | null
        }
        Update: {
          accion?: string
          created_at?: string
          id?: number
          ip_address?: unknown
          registro_id?: string
          tabla_afectada?: string
          usuario_id?: string | null
          valor_anterior?: Json | null
          valor_nuevo?: Json | null
        }
        Relationships: [
          {
            foreignKeyName: "audit_log_usuario_id_fkey"
            columns: ["usuario_id"]
            isOneToOne: false
            referencedRelation: "usuarios"
            referencedColumns: ["id"]
          },
        ]
      }
      cheques: {
        Row: {
          banco: string
          cliente_id: string | null
          created_at: string
          cuenta_bancaria: string | null
          estado: string
          fecha_cobro: string | null
          fecha_emision: string
          id: string
          importe: number
          notas: string | null
          numero: string
          origen: string
          proveedor_id: string | null
          tipo: string
          updated_at: string
        }
        Insert: {
          banco: string
          cliente_id?: string | null
          created_at?: string
          cuenta_bancaria?: string | null
          estado?: string
          fecha_cobro?: string | null
          fecha_emision: string
          id?: string
          importe: number
          notas?: string | null
          numero: string
          origen: string
          proveedor_id?: string | null
          tipo: string
          updated_at?: string
        }
        Update: {
          banco?: string
          cliente_id?: string | null
          created_at?: string
          cuenta_bancaria?: string | null
          estado?: string
          fecha_cobro?: string | null
          fecha_emision?: string
          id?: string
          importe?: number
          notas?: string | null
          numero?: string
          origen?: string
          proveedor_id?: string | null
          tipo?: string
          updated_at?: string
        }
        Relationships: []
      }
      claves_clientes: {
        Row: {
          clave: string
          cliente_id: string
          id: string
          notas: string | null
          tipo: string
          updated_at: string
          updated_by: string | null
          usuario: string | null
        }
        Insert: {
          clave: string
          cliente_id: string
          id?: string
          notas?: string | null
          tipo: string
          updated_at?: string
          updated_by?: string | null
          usuario?: string | null
        }
        Update: {
          clave?: string
          cliente_id?: string
          id?: string
          notas?: string | null
          tipo?: string
          updated_at?: string
          updated_by?: string | null
          usuario?: string | null
        }
        Relationships: []
      }
      clientes: {
        Row: {
          activo: boolean
          created_at: string
          cuit: string
          deleted_at: string | null
          domicilio: string | null
          email: string | null
          id: string
          localidad: string | null
          nombre: string
          notas: string | null
          responsable_id: string | null
          telefono: string | null
          updated_at: string
        }
        Insert: {
          activo?: boolean
          created_at?: string
          cuit: string
          deleted_at?: string | null
          domicilio?: string | null
          email?: string | null
          id?: string
          localidad?: string | null
          nombre: string
          notas?: string | null
          responsable_id?: string | null
          telefono?: string | null
          updated_at?: string
        }
        Update: {
          activo?: boolean
          created_at?: string
          cuit?: string
          deleted_at?: string | null
          domicilio?: string | null
          email?: string | null
          id?: string
          localidad?: string | null
          nombre?: string
          notas?: string | null
          responsable_id?: string | null
          telefono?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      compras_proveedores: {
        Row: {
          concepto: string
          created_at: string
          created_by: string | null
          estado: string
          fecha: string
          id: string
          importe_total: number
          notas: string | null
          nro_comprobante: string | null
          proveedor_id: string
          tipo_comprobante: string | null
          updated_at: string
        }
        Insert: {
          concepto: string
          created_at?: string
          created_by?: string | null
          estado?: string
          fecha: string
          id?: string
          importe_total: number
          notas?: string | null
          nro_comprobante?: string | null
          proveedor_id: string
          tipo_comprobante?: string | null
          updated_at?: string
        }
        Update: {
          concepto?: string
          created_at?: string
          created_by?: string | null
          estado?: string
          fecha?: string
          id?: string
          importe_total?: number
          notas?: string | null
          nro_comprobante?: string | null
          proveedor_id?: string
          tipo_comprobante?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      empleadas: {
        Row: {
          activo: boolean
          created_at: string
          deleted_at: string | null
          id: string
          nombre: string
          tipo_relacion: string
          usuario_id: string | null
        }
        Insert: {
          activo?: boolean
          created_at?: string
          deleted_at?: string | null
          id?: string
          nombre: string
          tipo_relacion: string
          usuario_id?: string | null
        }
        Update: {
          activo?: boolean
          created_at?: string
          deleted_at?: string | null
          id?: string
          nombre?: string
          tipo_relacion?: string
          usuario_id?: string | null
        }
        Relationships: []
      }
      fondos_movimientos: {
        Row: {
          cheque_id: string | null
          concepto: string
          created_at: string
          created_by: string | null
          cuenta_bancaria: string | null
          fecha: string
          id: string
          importe_banco: number | null
          importe_efectivo: number | null
          importe_usd: number | null
          nro_comprobante: string | null
          referencia_id: string | null
          referencia_tipo: string | null
          tipo_movimiento: string
        }
        Insert: {
          cheque_id?: string | null
          concepto: string
          created_at?: string
          created_by?: string | null
          cuenta_bancaria?: string | null
          fecha: string
          id?: string
          importe_banco?: number | null
          importe_efectivo?: number | null
          importe_usd?: number | null
          nro_comprobante?: string | null
          referencia_id?: string | null
          referencia_tipo?: string | null
          tipo_movimiento: string
        }
        Update: {
          cheque_id?: string | null
          concepto?: string
          created_at?: string
          created_by?: string | null
          cuenta_bancaria?: string | null
          fecha?: string
          id?: string
          importe_banco?: number | null
          importe_efectivo?: number | null
          importe_usd?: number | null
          nro_comprobante?: string | null
          referencia_id?: string | null
          referencia_tipo?: string | null
          tipo_movimiento?: string
        }
        Relationships: []
      }
      categorias_gastos: {
        Row: {
          activo: boolean
          color: string | null
          created_at: string
          created_by: string | null
          id: string
          nombre: string
          updated_at: string
        }
        Insert: {
          activo?: boolean
          color?: string | null
          created_at?: string
          created_by?: string | null
          id?: string
          nombre: string
          updated_at?: string
        }
        Update: {
          activo?: boolean
          color?: string | null
          created_at?: string
          created_by?: string | null
          id?: string
          nombre?: string
          updated_at?: string
        }
        Relationships: []
      }
      gastos_recurrentes: {
        Row: {
          activo: boolean
          categoria_id: string
          created_at: string
          created_by: string | null
          descripcion: string
          dia_vencimiento: number
          id: string
          notas: string | null
          proxima_fecha_vencimiento: string
          updated_at: string
        }
        Insert: {
          activo?: boolean
          categoria_id: string
          created_at?: string
          created_by?: string | null
          descripcion: string
          dia_vencimiento: number
          id?: string
          notas?: string | null
          proxima_fecha_vencimiento: string
          updated_at?: string
        }
        Update: {
          activo?: boolean
          categoria_id?: string
          created_at?: string
          created_by?: string | null
          descripcion?: string
          dia_vencimiento?: number
          id?: string
          notas?: string | null
          proxima_fecha_vencimiento?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "gastos_recurrentes_categoria_id_fkey"
            columns: ["categoria_id"]
            isOneToOne: false
            referencedRelation: "categorias_gastos"
            referencedColumns: ["id"]
          },
        ]
      }
      pagos_gastos: {
        Row: {
          categoria_id: string
          comprobante_url: string | null
          concepto: string
          created_at: string
          created_by: string | null
          fecha_pago: string
          fecha_vencimiento_pagado: string | null
          gasto_recurrente_id: string | null
          id: string
          importe: number
          medio_pago: string
          notas: string | null
          updated_at: string
        }
        Insert: {
          categoria_id: string
          comprobante_url?: string | null
          concepto: string
          created_at?: string
          created_by?: string | null
          fecha_pago: string
          fecha_vencimiento_pagado?: string | null
          gasto_recurrente_id?: string | null
          id?: string
          importe: number
          medio_pago: string
          notas?: string | null
          updated_at?: string
        }
        Update: {
          categoria_id?: string
          comprobante_url?: string | null
          concepto?: string
          created_at?: string
          created_by?: string | null
          fecha_pago?: string
          fecha_vencimiento_pagado?: string | null
          gasto_recurrente_id?: string | null
          id?: string
          importe?: number
          medio_pago?: string
          notas?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "pagos_gastos_categoria_id_fkey"
            columns: ["categoria_id"]
            isOneToOne: false
            referencedRelation: "categorias_gastos"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "pagos_gastos_gasto_recurrente_id_fkey"
            columns: ["gasto_recurrente_id"]
            isOneToOne: false
            referencedRelation: "gastos_recurrentes"
            referencedColumns: ["id"]
          },
        ]
      }
      honorarios_anuales: {
        Row: {
          anio: number
          asignado_a: string | null
          cliente_id: string
          created_at: string
          estado: string
          honorario: number | null
          id: string
          notas: string | null
          tipo_trabajo: string
          updated_at: string
        }
        Insert: {
          anio: number
          asignado_a?: string | null
          cliente_id: string
          created_at?: string
          estado?: string
          honorario?: number | null
          id?: string
          notas?: string | null
          tipo_trabajo: string
          updated_at?: string
        }
        Update: {
          anio?: number
          asignado_a?: string | null
          cliente_id?: string
          created_at?: string
          estado?: string
          honorario?: number | null
          id?: string
          notas?: string | null
          tipo_trabajo?: string
          updated_at?: string
        }
        Relationships: []
      }
      honorarios_mensuales: {
        Row: {
          cliente_id: string
          creado_por: string | null
          created_at: string
          frecuencia_ajuste_meses: number
          id: string
          monto: number
          notas: string | null
          porcentaje_ajuste: number | null
          vigente_desde: string
          vigente_hasta: string | null
        }
        Insert: {
          cliente_id: string
          creado_por?: string | null
          created_at?: string
          frecuencia_ajuste_meses?: number
          id?: string
          monto: number
          notas?: string | null
          porcentaje_ajuste?: number | null
          vigente_desde: string
          vigente_hasta?: string | null
        }
        Update: {
          cliente_id?: string
          creado_por?: string | null
          created_at?: string
          frecuencia_ajuste_meses?: number
          id?: string
          monto?: number
          notas?: string | null
          porcentaje_ajuste?: number | null
          vigente_desde?: string
          vigente_hasta?: string | null
        }
        Relationships: []
      }
      imputaciones: {
        Row: {
          created_at: string
          created_by: string | null
          id: string
          importe: number
          liquidacion_id: string
          notas: string | null
          recibo_id: string
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          id?: string
          importe: number
          liquidacion_id: string
          notas?: string | null
          recibo_id: string
        }
        Update: {
          created_at?: string
          created_by?: string | null
          id?: string
          importe?: number
          liquidacion_id?: string
          notas?: string | null
          recibo_id?: string
        }
        Relationships: []
      }
      liquidaciones: {
        Row: {
          cliente_id: string
          created_at: string
          detalle: string | null
          estado: string
          fecha_liquidacion: string
          generado_por: string | null
          id: string
          importe_facturado: number | null
          importe_liquidado: number
          notas: string | null
          nro_comprobante: string | null
          periodo_anio: number | null
          periodo_mes: string | null
          tipo_comprobante: string | null
          tipo_liquidacion: string
          tipo_servicio: string
          updated_at: string
        }
        Insert: {
          cliente_id: string
          created_at?: string
          detalle?: string | null
          estado?: string
          fecha_liquidacion: string
          generado_por?: string | null
          id?: string
          importe_facturado?: number | null
          importe_liquidado: number
          notas?: string | null
          nro_comprobante?: string | null
          periodo_anio?: number | null
          periodo_mes?: string | null
          tipo_comprobante?: string | null
          tipo_liquidacion?: string
          tipo_servicio: string
          updated_at?: string
        }
        Update: {
          cliente_id?: string
          created_at?: string
          detalle?: string | null
          estado?: string
          fecha_liquidacion?: string
          generado_por?: string | null
          id?: string
          importe_facturado?: number | null
          importe_liquidado?: number
          notas?: string | null
          nro_comprobante?: string | null
          periodo_anio?: number | null
          periodo_mes?: string | null
          tipo_comprobante?: string | null
          tipo_liquidacion?: string
          tipo_servicio?: string
          updated_at?: string
        }
        Relationships: []
      }
      liquidaciones_empleadas: {
        Row: {
          concepto: string
          created_at: string
          empleada_id: string
          id: string
          importe: number
          observaciones: string | null
          periodo_anio: number
          periodo_mes: number
          tipo_concepto: string
        }
        Insert: {
          concepto: string
          created_at?: string
          empleada_id: string
          id?: string
          importe: number
          observaciones?: string | null
          periodo_anio: number
          periodo_mes: number
          tipo_concepto: string
        }
        Update: {
          concepto?: string
          created_at?: string
          empleada_id?: string
          id?: string
          importe?: number
          observaciones?: string | null
          periodo_anio?: number
          periodo_mes?: number
          tipo_concepto?: string
        }
        Relationships: []
      }
      pagos_empleadas: {
        Row: {
          cheque_id: string | null
          created_at: string
          cuenta_bancaria: string | null
          empleada_id: string
          fecha_pago: string
          id: string
          importe: number
          notas: string | null
          periodo_anio: number
          periodo_mes: number
          tipo_pago: string
        }
        Insert: {
          cheque_id?: string | null
          created_at?: string
          cuenta_bancaria?: string | null
          empleada_id: string
          fecha_pago: string
          id?: string
          importe: number
          notas?: string | null
          periodo_anio: number
          periodo_mes: number
          tipo_pago: string
        }
        Update: {
          cheque_id?: string | null
          created_at?: string
          cuenta_bancaria?: string | null
          empleada_id?: string
          fecha_pago?: string
          id?: string
          importe?: number
          notas?: string | null
          periodo_anio?: number
          periodo_mes?: number
          tipo_pago?: string
        }
        Relationships: []
      }
      pagos_proveedores: {
        Row: {
          cheque_id: string | null
          compra_id: string
          created_at: string
          cuenta_bancaria: string | null
          fecha_pago: string
          id: string
          importe: number
          notas: string | null
          tipo_pago: string
        }
        Insert: {
          cheque_id?: string | null
          compra_id: string
          created_at?: string
          cuenta_bancaria?: string | null
          fecha_pago: string
          id?: string
          importe: number
          notas?: string | null
          tipo_pago: string
        }
        Update: {
          cheque_id?: string | null
          compra_id?: string
          created_at?: string
          cuenta_bancaria?: string | null
          fecha_pago?: string
          id?: string
          importe?: number
          notas?: string | null
          tipo_pago?: string
        }
        Relationships: []
      }
      parametros: {
        Row: {
          activo: boolean
          categoria: string
          codigo: string
          descripcion: string
          id: string
          orden: number | null
        }
        Insert: {
          activo?: boolean
          categoria: string
          codigo: string
          descripcion: string
          id?: string
          orden?: number | null
        }
        Update: {
          activo?: boolean
          categoria?: string
          codigo?: string
          descripcion?: string
          id?: string
          orden?: number | null
        }
        Relationships: []
      }
      proveedores: {
        Row: {
          activo: boolean
          created_at: string
          cuit: string | null
          deleted_at: string | null
          email: string | null
          id: string
          nombre: string
          notas: string | null
          rubro: string | null
          telefono: string | null
        }
        Insert: {
          activo?: boolean
          created_at?: string
          cuit?: string | null
          deleted_at?: string | null
          email?: string | null
          id?: string
          nombre: string
          notas?: string | null
          rubro?: string | null
          telefono?: string | null
        }
        Update: {
          activo?: boolean
          created_at?: string
          cuit?: string | null
          deleted_at?: string | null
          email?: string | null
          id?: string
          nombre?: string
          notas?: string | null
          rubro?: string | null
          telefono?: string | null
        }
        Relationships: []
      }
      recibos: {
        Row: {
          anulado: boolean
          anulado_at: string | null
          anulado_by: string | null
          cheque_id: string | null
          cliente_id: string
          created_at: string
          created_by: string | null
          cuenta_bancaria: string | null
          fecha: string
          id: string
          importe: number
          importe_usd: number | null
          motivo_anulacion: string | null
          notas: string | null
          numero_recibo: string | null
          tipo_cambio: number | null
          tipo_pago: string
          updated_at: string
        }
        Insert: {
          anulado?: boolean
          anulado_at?: string | null
          anulado_by?: string | null
          cheque_id?: string | null
          cliente_id: string
          created_at?: string
          created_by?: string | null
          cuenta_bancaria?: string | null
          fecha: string
          id?: string
          importe: number
          importe_usd?: number | null
          motivo_anulacion?: string | null
          notas?: string | null
          numero_recibo?: string | null
          tipo_cambio?: number | null
          tipo_pago: string
          updated_at?: string
        }
        Update: {
          anulado?: boolean
          anulado_at?: string | null
          anulado_by?: string | null
          cheque_id?: string | null
          cliente_id?: string
          created_at?: string
          created_by?: string | null
          cuenta_bancaria?: string | null
          fecha?: string
          id?: string
          importe?: number
          importe_usd?: number | null
          motivo_anulacion?: string | null
          notas?: string | null
          numero_recibo?: string | null
          tipo_cambio?: number | null
          tipo_pago?: string
          updated_at?: string
        }
        Relationships: []
      }
      usuarios: {
        Row: {
          activo: boolean
          created_at: string
          email: string
          id: string
          nombre: string
          rol: string
          updated_at: string
        }
        Insert: {
          activo?: boolean
          created_at?: string
          email: string
          id: string
          nombre: string
          rol: string
          updated_at?: string
        }
        Update: {
          activo?: boolean
          created_at?: string
          email?: string
          id?: string
          nombre?: string
          rol?: string
          updated_at?: string
        }
        Relationships: []
      }
    }
    Views: {
      v_pagos_gastos_detalle: {
        Row: {
          anio: number | null
          categoria_color: string | null
          categoria_id: string | null
          categoria_nombre: string | null
          comprobante_url: string | null
          concepto: string | null
          fecha_pago: string | null
          fecha_vencimiento_pagado: string | null
          gasto_descripcion: string | null
          gasto_recurrente_id: string | null
          id: string | null
          importe: number | null
          medio_pago: string | null
          mes: number | null
          notas: string | null
        }
        Relationships: [
          {
            foreignKeyName: "pagos_gastos_categoria_id_fkey"
            columns: ["categoria_id"]
            isOneToOne: false
            referencedRelation: "categorias_gastos"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "pagos_gastos_gasto_recurrente_id_fkey"
            columns: ["gasto_recurrente_id"]
            isOneToOne: false
            referencedRelation: "gastos_recurrentes"
            referencedColumns: ["id"]
          },
        ]
      }
      v_proximos_vencimientos: {
        Row: {
          categoria_color: string | null
          categoria_id: string | null
          categoria_nombre: string | null
          descripcion: string | null
          dia_vencimiento: number | null
          dias_restantes: number | null
          gasto_id: string | null
          proxima_fecha_vencimiento: string | null
        }
        Relationships: []
      }
      v_cuenta_corriente: {
        Row: {
          cliente_id: string | null
          cliente_nombre: string | null
          liquidaciones_pendientes: number | null
          saldo_a_favor: number | null
          saldo_pendiente: number | null
          total_cobrado: number | null
          total_devengado: number | null
          total_imputado: number | null
          total_recibido: number | null
        }
        Relationships: []
      }
      v_imputaciones_detalle: {
        Row: {
          cliente_id: string | null
          created_at: string | null
          fecha_liquidacion: string | null
          id: string | null
          importe: number | null
          importe_liquidado: number | null
          liquidacion_detalle: string | null
          liquidacion_id: string | null
          notas: string | null
          numero_recibo: string | null
          recibo_fecha: string | null
          recibo_id: string | null
          recibo_tipo_pago: string | null
          tipo_servicio: string | null
        }
        Relationships: []
      }
      v_recibos_disponibles: {
        Row: {
          anulado: boolean | null
          cheque_id: string | null
          cliente_id: string | null
          created_at: string | null
          cuenta_bancaria: string | null
          fecha: string | null
          id: string | null
          importe: number | null
          importe_usd: number | null
          notas: string | null
          numero_recibo: string | null
          saldo_libre: number | null
          tipo_cambio: number | null
          tipo_pago: string | null
          total_imputado: number | null
        }
        Relationships: []
      }
      v_saldo_fondos: {
        Row: {
          saldo_banco: number | null
          saldo_efectivo: number | null
          saldo_usd: number | null
        }
        Relationships: []
      }
    }
    Functions: {
      fn_avanzar_vencimiento: {
        Args: { p_gasto_id: string }
        Returns: string
      }
      fn_calcular_proxima_fecha_gasto: {
        Args: { p_desde?: string; p_dia: number }
        Returns: string
      }
      fn_registrar_pago_gasto: {
        Args: {
          p_categoria_id: string
          p_comprobante_url?: string
          p_concepto: string
          p_fecha_pago: string
          p_gasto_recurrente_id?: string
          p_importe: number
          p_medio_pago: string
          p_notas?: string
        }
        Returns: Database["public"]["Tables"]["pagos_gastos"]["Row"]
      }
      fn_anular_recibo: {
        Args: { p_motivo?: string; p_recibo_id: string }
        Returns: Database["public"]["Tables"]["recibos"]["Row"]
      }
      fn_aplicar_ajuste_honorario: {
        Args: {
          p_cliente_id: string
          p_frecuencia_meses?: number
          p_notas?: string
          p_porcentaje: number
        }
        Returns: Database["public"]["Tables"]["honorarios_mensuales"]["Row"]
      }
      fn_eliminar_imputacion: {
        Args: { p_imputacion_id: string }
        Returns: boolean
      }
      fn_imputar_recibo: {
        Args: {
          p_importe: number
          p_liquidacion_id: string
          p_notas?: string
          p_recibo_id: string
        }
        Returns: Database["public"]["Tables"]["imputaciones"]["Row"]
      }
      fn_recalcular_estado_liquidacion: {
        Args: { p_liquidacion_id: string }
        Returns: string
      }
      fn_registrar_pago_proveedor: {
        Args: {
          p_cheque_id?: string
          p_compra_id: string
          p_cuenta_bancaria?: string
          p_fecha_pago: string
          p_importe: number
          p_notas?: string
          p_tipo_pago: string
        }
        Returns: Database["public"]["Tables"]["pagos_proveedores"]["Row"]
      }
      fn_registrar_recibo: {
        Args: {
          p_cheque_id?: string
          p_cliente_id: string
          p_cuenta_bancaria?: string
          p_fecha: string
          p_importe: number
          p_importe_usd?: number
          p_imputaciones?: Json
          p_notas?: string
          p_numero_recibo?: string
          p_tipo_cambio?: number
          p_tipo_pago: string
        }
        Returns: Database["public"]["Tables"]["recibos"]["Row"]
      }
      is_admin: { Args: never; Returns: boolean }
      is_authenticated_user: { Args: never; Returns: boolean }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
